releases:
  - name: portfolio
    chart: ./charts/portfolio
    version: 0.1.0
    set:
      - name: podLabels.commit
        value: {{ requiredEnv "SHORT_SHA" }}
      - name: image.repository
        value: {{ requiredEnv "_IMAGE_REPO" }}
      - name: image.tag
        value: {{ requiredEnv "_IMAGE_TAG" }}
      - name: service.port
        value: 3000
      - name: ingress.globalStaticIPName
        value: portfolio-ip-global